<a href="https://colab.research.google.com/github/kimcheese23/Data-analytics/blob/main/Code/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
folder = '/content/drive/MyDrive/PTDL'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 1. File và thư viện

In [2]:
# Thêm các thư viện
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import string as st
warnings.filterwarnings('ignore')

Dataset: https://www.kaggle.com/datasets/divyansh22/online-gaming-anxiety-data/code

In [3]:
df_raw = pd.read_csv('/content/drive/MyDrive/PTDL/GamingStudy_data.csv', encoding='latin1')
df_raw.head(5).T

,0,1,2,3,4
S. No.,1,2,3,4,5
Timestamp,42052.00437,42052.0068,42052.0386,42052.06804,42052.08948
GAD1,0,1,0,0,2
GAD2,0,2,2,0,1
GAD3,0,2,2,0,2
GAD4,0,2,0,0,2
GAD5,1,0,0,0,2
GAD6,0,1,3,0,3
GAD7,0,0,1,0,2
GADE,Not difficult at all,Somewhat difficult,Not difficult at all,Not difficult at all,Very difficult
SWL1,3,3,2,2,2
SWL2,5,5,6,5,2
SWL3,5,2,5,5,4
SWL4,5,5,2,3,5
SWL5,5,1,2,2,1
Game,Skyrim,Other,Other,Other,Other
Platform,"Console (PS, Xbox, ...)",PC,PC,PC,"Console (PS, Xbox, ...)"
Hours,15.0,8.0,0.0,20.0,20.0
earnings,I play for fun,I play for fun,I play for fun,I play for fun,I play for fun
whyplay,having fun,having fun,having fun,improving,having fun
League,NaN,NaN,NaN,NaN,NaN
highestleague,NaN,NaN,NaN,NaN,NaN
streams,0.0,2.0,0.0,5.0,1.0
SPIN1,1.0,2.0,1.0,2.0,2.0
SPIN2,0.0,1.0,0.0,0.0,0.0
SPIN3,0.0,1.0,1.0,0.0,0.0
SPIN4,1.0,3.0,2.0,1.0,0.0
SPIN5,0.0,2.0,3.0,3.0,1.0
SPIN6,0.0,3.0,4.0,0.0,0.0
SPIN7,1.0,1.0,2.0,0.0,0.0
SPIN8,0.0,3.0,1.0,0.0,4.0
SPIN9,0.0,4.0,0.0,0.0,2.0
SPIN10,0.0,0.0,1.0,0.0,0.0
SPIN11,0.0,3.0,1.0,1.0,1.0
SPIN12,0.0,0.0,3.0,3.0,0.0
SPIN13,0.0,1.0,0.0,0.0,0.0
SPIN14,1.0,3.0,2.0,0.0,0.0
SPIN15,0.0,3.0,4.0,1.0,0.0
SPIN16,1.0,1.0,4.0,0.0,3.0
SPIN17,0.0,2.0,2.0,0.0,0.0
Narcissism,1.0,1.0,4.0,2.0,1.0
Gender,Male,Male,Female,Male,Male
Age,25,41,32,28,19
Work,Unemployed / between jobs,Unemployed / between jobs,Employed,Employed,Employed
Degree,Bachelor (or equivalent),Bachelor (or equivalent),Bachelor (or equivalent),Bachelor (or equivalent),High school diploma (or equivalent)
Birthplace,USA,USA,Germany,USA,USA
Residence,USA,USA,Germany,USA,South Korea
Reference,Reddit,Reddit,Reddit,Reddit,Reddit
Playstyle,Singleplayer,Multiplayer - online - with strangers,Singleplayer,Multiplayer - online - with online acquaintanc...,Multiplayer - online - with strangers
accept,Accept,Accept,Accept,Accept,Accept
GAD_T,1,8,8,0,14
SWL_T,23,16,17,17,14
SPIN_T,5.0,33.0,31.0,11.0,13.0
Residence_ISO3,USA,USA,DEU,USA,KOR
Birthplace_ISO3,USA,USA,DEU,USA,USA

# 2. Khám phá dữ liệu

Tìm hiểu dữ liệu

In [4]:
df = df_raw.copy()
print(f'Dữ liệu có {df.shape[0]} dòng quan sát và {df.shape[1]} cột thuộc tính.')

Dữ liệu có 13464 dòng quan sát và 55 cột thuộc tính.

In [5]:
df.columns

Index(['S. No.', 'Timestamp', 'GAD1', 'GAD2', 'GAD3', 'GAD4', 'GAD5', 'GAD6',
       'GAD7', 'GADE', 'SWL1', 'SWL2', 'SWL3', 'SWL4', 'SWL5', 'Game',
       'Platform', 'Hours', 'earnings', 'whyplay', 'League', 'highestleague',
       'streams', 'SPIN1', 'SPIN2', 'SPIN3', 'SPIN4', 'SPIN5', 'SPIN6',
       'SPIN7', 'SPIN8', 'SPIN9', 'SPIN10', 'SPIN11', 'SPIN12', 'SPIN13',
       'SPIN14', 'SPIN15', 'SPIN16', 'SPIN17', 'Narcissism', 'Gender', 'Age',
       'Work', 'Degree', 'Birthplace', 'Residence', 'Reference', 'Playstyle',
       'accept', 'GAD_T', 'SWL_T', 'SPIN_T', 'Residence_ISO3',
       'Birthplace_ISO3'],
      dtype='object')

In [6]:
print('Số giá trị bị thiếu trong tập dữ liệu: ', df.isnull().sum().sum())
print('Số dòng trùng: ', df.duplicated().sum())

Số giá trị bị thiếu trong tập dữ liệu:  21709
Số dòng trùng:  0

In [7]:
def value_check(dataframe):
    dataframe_check = pd.DataFrame({
        'Count': dataframe.count(),
        'Unique': dataframe.nunique(),
        'Null': dataframe.isnull().sum(),
        '%Null': (dataframe.isnull().sum() / len(dataframe)) * 100,
        'DType': dataframe.dtypes.values
    })
    dataframe_check['%Null'] = dataframe_check['%Null'].map('{:.2f}%'.format)
    return dataframe_check

In [8]:
value_check(df)

                 Count  Unique   Null    %Null    DType
S. No.           13464   13464      0    0.00%    int64
Timestamp        13464   11734      0    0.00%  float64
GAD1             13464       4      0    0.00%    int64
GAD2             13464       4      0    0.00%    int64
GAD3             13464       4      0    0.00%    int64
GAD4             13464       4      0    0.00%    int64
GAD5             13464       4      0    0.00%    int64
GAD6             13464       4      0    0.00%    int64
GAD7             13464       4      0    0.00%    int64
GADE             12815       4    649    4.82%   object
SWL1             13464       7      0    0.00%    int64
SWL2             13464       7      0    0.00%    int64
SWL3             13464       7      0    0.00%    int64
SWL4             13464       7      0    0.00%    int64
SWL5             13464       7      0    0.00%    int64
Game             13464      11      0    0.00%   object
Platform         13464       3      0    0.00%   object
Hours            13434      84     30    0.22%  float64
earnings         13464     314      0    0.00%   object
whyplay          13464     407      0    0.00%   object
League           11612    1454   1852   13.76%   object
highestleague        0       0  13464  100.00%  float64
streams          13364      65    100    0.74%  float64
SPIN1            13340       5    124    0.92%  float64
SPIN2            13310       5    154    1.14%  float64
SPIN3            13324       5    140    1.04%  float64
SPIN4            13305       5    159    1.18%  float64
SPIN5            13298       5    166    1.23%  float64
SPIN6            13308       5    156    1.16%  float64
SPIN7            13326       5    138    1.02%  float64
SPIN8            13320       5    144    1.07%  float64
SPIN9            13306       5    158    1.17%  float64
SPIN10           13304       5    160    1.19%  float64
SPIN11           13277       5    187    1.39%  float64
SPIN12           13296       5    168    1.25%  float64
SPIN13           13277       5    187    1.39%  float64
SPIN14           13308       5    156    1.16%  float64
SPIN15           13317       5    147    1.09%  float64
SPIN16           13317       5    147    1.09%  float64
SPIN17           13289       5    175    1.30%  float64
Narcissism       13441       5     23    0.17%  float64
Gender           13464       3      0    0.00%   object
Age              13464      30      0    0.00%    int64
Work             13426       4     38    0.28%   object
Degree           11887       4   1577   11.71%   object
Birthplace       13464     126      0    0.00%   object
Residence        13464     109      0    0.00%   object
Reference        13449       4     15    0.11%   object
Playstyle        13464     298      0    0.00%   object
accept           13050       1    414    3.07%   object
GAD_T            13464      22      0    0.00%    int64
SWL_T            13464      31      0    0.00%    int64
SPIN_T           12814      69    650    4.83%  float64
Residence_ISO3   13354     107    110    0.82%   object
Birthplace_ISO3  13343     124    121    0.90%   object

In [9]:
print('\nThống kê mô tả các biến định lượng:')
df.describe().style.format('{:.2f}')

Thống kê mô tả các biến định lượng:

In [10]:
print('\nThống kê mô tả các biến kiểu object:')
df.describe(include=['O'])

Thống kê mô tả các biến kiểu object:

,GADE,Game,Platform,earnings,whyplay,League,Gender,Work,Degree,Birthplace,Residence,Reference,Playstyle,accept,Residence_ISO3,Birthplace_ISO3
count,12815,13464,13464,13464,13464,11612,13464,13426,11887,13464,13464,13449,13464,13050,13354,13343
unique,4,11,3,314,407,1454,3,4,4,126,109,4,298,1,107,124
top,Not difficult at all,League of Legends,PC,I play for fun,having fun,Gold,Male,Student at college / university,High school diploma (or equivalent),USA,USA,Reddit,Multiplayer - online - with real life friends,Accept,USA,USA
freq,6236,11314,13219,12112,5289,970,12699,7073,8560,4261,4569,13324,5564,13050,4569,4261

Thống kê chi tiết từng biến

In [11]:
var_count = ['Game', 'Platform', 'Narcissism', 'Gender', 'Age',
        'Work', 'Degree', 'Reference', 'accept']
for i in var_count:
    print(df[i].value_counts())
    print('*'*40)

Game
League of Legends      11314
Other                   1021
Starcraft 2              345
Counter Strike           318
World of Warcraft        152
Hearthstone              101
Diablo 3                  89
Heroes of the Storm       41
Guild Wars 2              37
Skyrim                    28
Destiny                   18
Name: count, dtype: int64
****************************************
Platform
PC                         13219
Console (PS, Xbox, ...)      222
Smartphone / Tablet           23
Name: count, dtype: int64
****************************************
Narcissism
1.0    5259
2.0    4360
3.0    2341
4.0    1153
5.0     328
Name: count, dtype: int64
****************************************
Gender
Male      12699
Female      713
Other        52
Name: count, dtype: int64
****************************************
Age
18    3588
19    2159
20    1855
21    1507
22    1135
23     872
24     660
25     514
26     338
27     231
28     157
29     119
30      89
31      58
32      53
33      37
34      19
35      17
36      16
38       8
42       6
39       6
37       5
41       4
50       3
40       3
44       2
63       1
49       1
56       1
Name: count, dtype: int64
****************************************
Work
Student at college / university    7073
Employed                           2734
Student at school                  2229
Unemployed / between jobs          1390
Name: count, dtype: int64
****************************************
Degree
High school diploma (or equivalent)    8560
Bachelor (or equivalent)               2687
Master (or equivalent)                  546
Ph.D., Psy. D., MD (or equivalent)       94
Name: count, dtype: int64
****************************************
Reference
Reddit            13324
Other                67
TeamLiquid.net       55
CrowdFlower           3
Name: count, dtype: int64
****************************************
accept
Accept    13050
Name: count, dtype: int64
****************************************

In [12]:
psy_count = ['GAD_T', 'SWL_T', 'SPIN_T']
for i in psy_count:
    print(df[i].value_counts().head(20))
    print('*'*40)

GAD_T
0     1669
2     1618
1     1485
3     1455
4     1219
5     1024
6      849
7      720
8      598
9      475
10     407
11     367
12     308
13     292
14     239
15     160
16     144
21     131
17     113
18      86
Name: count, dtype: int64
****************************************
SWL_T
24    636
20    607
18    606
22    600
21    595
15    590
19    588
23    587
17    580
16    576
25    569
26    568
14    550
27    540
28    525
13    503
30    477
12    476
10    441
29    425
Name: count, dtype: int64
****************************************
SPIN_T
14.0    444
11.0    443
12.0    440
7.0     426
13.0    413
8.0     409
10.0    408
9.0     401
17.0    395
15.0    388
16.0    380
5.0     357
19.0    351
18.0    351
6.0     349
4.0     341
20.0    330
21.0    325
22.0    306
3.0     299
Name: count, dtype: int64
****************************************

In [13]:
df.Hours.value_counts()

Hours
20.0     2293
10.0     1375
30.0     1186
15.0     1115
25.0      831
         ...
420.0       1
110.0       1
112.0       1
96.0        1
150.0       1
Name: count, Length: 84, dtype: int64

In [14]:
df.earnings.value_counts().head(10)

earnings
I play for fun                                                                               12112
I play mostly for fun but earn a little on the side (tournament winnings, streaming, etc)      990
I earn a living by playing this game                                                            48
I play to win                                                                                    3
i try                                                                                            2
for my ear                                                                                       1
I don't earn jack ****                                                                           1
I play for relaxation and it gives me a few minutes to release everything                        1
making money from boosting,but mostly fun                                                        1
I play because it's installed                                                                    1
Name: count, dtype: int64

In [15]:
df.whyplay.value_counts().head(20)

whyplay
having fun                      5289
improving                       4927
winning                         2091
relaxing                         654
All of the above                  26
all of the above                  22
Improving and having fun          10
improving and having fun           8
winning and improving              6
having fun and improving           5
distraction                        4
Wasting time                       4
winning while having fun           3
both relaxing and having fun       3
All                                3
relaxing and having fun            3
winning and relaxing               2
improving and winning              2
Having fun and improving           2
playing with friends               2
Name: count, dtype: int64

In [16]:
df.Playstyle.value_counts().head(10)

Playstyle
Multiplayer - online - with real life friends                    5564
Multiplayer - online - with strangers                            4134
Multiplayer - online - with online acquaintances or teammates    2652
Singleplayer                                                      762
Multiplayer - offline (people in the same room)                    48
all of the above                                                    7
All of the above                                                    6
Multiplayer with online friends and real life friends.              1
Multiplayer-online-real life friends and online acquaintances       1
Equal mix of real life friends and online                           1
Name: count, dtype: int64

In [17]:
df.League.value_counts().head(10)

League
Gold         970
Silver       650
Platinum     635
Diamond      549
gold         316
Unranked     264
Diamond 5    217
silver       212
Gold V       205
Gold 1       202
Name: count, dtype: int64

In [18]:
df.Residence_ISO3.value_counts()

Residence_ISO3
USA    4569
DEU    1413
GBR    1032
CAN     994
NLD     506
       ...
VCT       1
BRN       1
FJI       1
GIB       1
PSE       1
Name: count, Length: 107, dtype: int64

# 3. Tiền xử lý dữ liệu

Xử lý các cột không cần thiết trong phân tích


*   Bỏ cột dữ liệu trống hoàn toàn highestleague
*   Bỏ cột không liên quan trong phân tích gồm: S. No, Timestamp, Birthplace, Birthplace_ISO3, Residence, Reference, accept, **League** (nếu có tgian sẽ xử lý thêm)

In [19]:
cols_to_drop = ['S. No.', 'Timestamp', 'highestleague', 'Birthplace', 'Birthplace_ISO3', 'Residence', 'Reference', 'accept', 'League']
existing_cols_to_drop = [col for col in cols_to_drop if col in df.columns]
df = df.drop(columns=existing_cols_to_drop)
df.shape

(13464, 46)

3.1 Xử lí giá trị null

In [20]:
df['Hours'] = df['Hours'].fillna(df['Hours'].median())

In [21]:
df['Narcissism'] = df['Narcissism'].fillna(df['Narcissism'].median())
df.Narcissism.value_counts()

Narcissism
1.0    5259
2.0    4383
3.0    2341
4.0    1153
5.0     328
Name: count, dtype: int64

In [22]:
df['streams'] = df['streams'].fillna(0)

In [23]:
df['Degree'] = df['Degree'].fillna('Other')
df.Degree.value_counts()

Degree
High school diploma (or equivalent)    8560
Bachelor (or equivalent)               2687
Other                                  1577
Master (or equivalent)                  546
Ph.D., Psy. D., MD (or equivalent)       94
Name: count, dtype: int64

In [24]:
df['Work'] = df['Work'].fillna('Other')
df.Work.value_counts()

Work
Student at college / university    7073
Employed                           2734
Student at school                  2229
Unemployed / between jobs          1390
Other                                38
Name: count, dtype: int64

In [25]:
df['Residence_ISO3'] = df['Residence_ISO3'].fillna('Other')
df.Residence_ISO3.value_counts()

Residence_ISO3
USA    4569
DEU    1413
GBR    1032
CAN     994
NLD     506
       ...
VCT       1
BRN       1
FJI       1
GIB       1
PSE       1
Name: count, Length: 108, dtype: int64

In [26]:
condition = [
    (df['GAD_T'] >= 0) & (df['GAD_T'] <= 4),
    (df['GAD_T'] >= 5) & (df['GAD_T'] <= 9),
    (df['GAD_T'] >= 10) & (df['GAD_T'] <= 14),
    (df['GAD_T'] >= 15) & (df['GAD_T'] <= 21)
]
choice = [
    'Not difficult at all',
    'Somewhat difficult',
    'Very difficult',
    'Extremely difficult'
]
mapped_gade = np.select(condition, choice, default='')
df['GADE'] = df['GADE'].fillna(pd.Series(mapped_gade, index=df.index))

In [27]:
spin_cols = []
for i in range (1, 18):
    spin_cols.append(f'SPIN{i}')
df = df.dropna(subset=spin_cols, thresh=14)

In [28]:
df[spin_cols] = df[spin_cols].apply(lambda row: row.fillna(row.median()), axis=1)

In [29]:
# Tính lại SPIN_T
df['SPIN_T'] = df[spin_cols].sum(axis=1)

In [30]:
value_check(df)

                Count  Unique  Null  %Null    DType
GAD1            13338       4     0  0.00%    int64
GAD2            13338       4     0  0.00%    int64
GAD3            13338       4     0  0.00%    int64
GAD4            13338       4     0  0.00%    int64
GAD5            13338       4     0  0.00%    int64
GAD6            13338       4     0  0.00%    int64
GAD7            13338       4     0  0.00%    int64
GADE            13338       4     0  0.00%   object
SWL1            13338       7     0  0.00%    int64
SWL2            13338       7     0  0.00%    int64
SWL3            13338       7     0  0.00%    int64
SWL4            13338       7     0  0.00%    int64
SWL5            13338       7     0  0.00%    int64
Game            13338      11     0  0.00%   object
Platform        13338       3     0  0.00%   object
Hours           13338      84     0  0.00%  float64
earnings        13338     313     0  0.00%   object
whyplay         13338     402     0  0.00%   object
streams         13338      65     0  0.00%  float64
SPIN1           13338       6     0  0.00%  float64
SPIN2           13338       7     0  0.00%  float64
SPIN3           13338       8     0  0.00%  float64
SPIN4           13338       7     0  0.00%  float64
SPIN5           13338       8     0  0.00%  float64
SPIN6           13338       6     0  0.00%  float64
SPIN7           13338       5     0  0.00%  float64
SPIN8           13338       8     0  0.00%  float64
SPIN9           13338       8     0  0.00%  float64
SPIN10          13338       7     0  0.00%  float64
SPIN11          13338       8     0  0.00%  float64
SPIN12          13338       8     0  0.00%  float64
SPIN13          13338       8     0  0.00%  float64
SPIN14          13338       7     0  0.00%  float64
SPIN15          13338       7     0  0.00%  float64
SPIN16          13338       6     0  0.00%  float64
SPIN17          13338       8     0  0.00%  float64
Narcissism      13338       5     0  0.00%  float64
Gender          13338       3     0  0.00%   object
Age             13338      30     0  0.00%    int64
Work            13338       5     0  0.00%   object
Degree          13338       5     0  0.00%   object
Playstyle       13338     295     0  0.00%   object
GAD_T           13338      22     0  0.00%    int64
SWL_T           13338      31     0  0.00%    int64
SPIN_T          13338      98     0  0.00%  float64
Residence_ISO3  13338     108     0  0.00%   object

3.2 Xử lý giá trị outlier

In [31]:
df.drop(df[df.Hours >= 140].index, inplace=True)
df.drop(df[df.streams >= 140].index, inplace=True)

3.3 Chuẩn hóa dữ liệu

In [32]:
df['Playstyle'] = df['Playstyle'].apply(lambda x: ' '.join(word.strip(st.punctuation) for word in x.split()))
df['earnings'] = df['earnings'].apply(lambda x: ' '.join(word.strip(st.punctuation) for word in x.split()))
df['whyplay'] = df['whyplay'].apply(lambda x: ' '.join(word.strip(st.punctuation) for word in x.split()))

In [33]:
df['Playstyle'] = df['Playstyle'].str.lower().str.strip()
df['whyplay'] = df['whyplay'].str.lower().str.strip()
df['earnings'] = df['earnings'].str.lower().str.strip()

In [34]:
df.Playstyle.replace(df.Playstyle.value_counts().index[5:] , 'Other',inplace=True)
df['Playstyle'].value_counts()

Playstyle
multiplayer  online  with real life friends                    5504
multiplayer  online  with strangers                            4090
multiplayer  online  with online acquaintances or teammates    2637
singleplayer                                                    751
Other                                                           300
multiplayer  offline people in the same room                     48
Name: count, dtype: int64

In [35]:
df.whyplay.replace(df.whyplay.value_counts().index[5:] , 'Other',inplace=True)
df['whyplay'].value_counts()

whyplay
having fun          5253
improving           4876
winning             2056
relaxing             649
Other                440
all of the above      56
Name: count, dtype: int64

In [36]:
df.earnings.replace(df.earnings.value_counts().index[3:] , 'Other',inplace=True)
df['earnings'].value_counts()

earnings
i play for fun                                                                           12008
i play mostly for fun but earn a little on the side tournament winnings streaming etc      968
Other                                                                                      311
i earn a living by playing this game                                                        43
Name: count, dtype: int64

In [37]:
df.shape

(13330, 46)

In [38]:
# Xóa các cột điểm thành phần của GAD, SWLS, SPINS
gad_cols = []
for i in range (1, 8):
    gad_cols.append(f'GAD{i}')

swls_cols = []
for i in range (1, 6):
    swls_cols.append(f'SWL{i}')

df = df.drop(columns=gad_cols)
df = df.drop(columns=swls_cols)
df = df.drop(columns=spin_cols)

In [39]:
df.shape

(13330, 17)

# 4. Lưu file

In [40]:
df.to_csv(folder + '/GamingStudy_data_cleaned.csv', index = False)